# CMake generated Testfile for 
# Source directory: /home/runner/work/c-blosc2/c-blosc2/examples
# Build directory: /home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_example_contexts "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/contexts")
set_tests_properties(test_example_contexts PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_instrument_codec "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/instrument_codec")
set_tests_properties(test_example_instrument_codec PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_delta_schunk_ex "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/delta_schunk_ex")
set_tests_properties(test_example_delta_schunk_ex PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_multithread "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/multithread")
set_tests_properties(test_example_multithread PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_simple "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/simple")
set_tests_properties(test_example_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_metalayers "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_metalayers")
set_tests_properties(test_example_frame_metalayers PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_noinit "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/noinit")
set_tests_properties(test_example_noinit PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_find_roots "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/find_roots")
set_tests_properties(test_example_find_roots PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_schunk_simple "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/schunk_simple")
set_tests_properties(test_example_schunk_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_simple "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_simple")
set_tests_properties(test_example_frame_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_schunk_postfilter "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/schunk_postfilter")
set_tests_properties(test_example_schunk_postfilter PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_urcodecs "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/urcodecs")
set_tests_properties(test_example_urcodecs PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_urfilters "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/urfilters")
set_tests_properties(test_example_urfilters PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_vlmetalayers "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_vlmetalayers")
set_tests_properties(test_example_frame_vlmetalayers PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_sframe_simple "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/sframe_simple")
set_tests_properties(test_example_sframe_simple PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_backed_schunk "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_backed_schunk")
set_tests_properties(test_example_frame_backed_schunk PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_compress_file "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/compress_file" "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/CMakeCache.txt" "CMakeCache.b2frame")
set_tests_properties(test_example_compress_file PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;46;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_decompress_file "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/decompress_file" "CMakeCache.b2frame" "CMakeCache-2.txt")
set_tests_properties(test_example_decompress_file PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;50;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_offset "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_offset")
set_tests_properties(test_example_frame_offset PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_roundtrip "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_roundtrip")
set_tests_properties(test_example_frame_roundtrip PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_get_set_slice "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/get_set_slice")
set_tests_properties(test_example_get_set_slice PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_get_blocksize "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/get_blocksize")
set_tests_properties(test_example_get_blocksize PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_zstd_dict "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/zstd_dict")
set_tests_properties(test_example_zstd_dict PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
add_test(test_example_frame_big "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/examples/frame_big")
set_tests_properties(test_example_frame_big PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;54;add_test;/home/runner/work/c-blosc2/c-blosc2/examples/CMakeLists.txt;0;")
subdirs("b2nd")
