# CMake generated Testfile for 
# Source directory: /home/runner/work/c-blosc2/c-blosc2/bench
# Build directory: /home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_blosclz_shuffle_1 "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "blosclz" "shuffle" "test" "1")
set_tests_properties(test_blosclz_shuffle_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;63;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_lz4_shuffle_1 "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "lz4" "shuffle" "test" "1")
set_tests_properties(test_lz4_shuffle_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;65;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_blosclz_shuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "blosclz" "shuffle" "test")
set_tests_properties(test_blosclz_shuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;82;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_lz4_shuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "lz4" "shuffle" "test")
set_tests_properties(test_lz4_shuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;84;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_lz4hc_shuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "lz4hc" "shuffle" "test")
set_tests_properties(test_lz4hc_shuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;86;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_zlib_shuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "zlib" "shuffle" "test")
set_tests_properties(test_zlib_shuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;89;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_zstd_shuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "zstd" "shuffle" "test")
set_tests_properties(test_zstd_shuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;93;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_blosclz_bitshuffle_1 "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "blosclz" "bitshuffle" "test" "1")
set_tests_properties(test_blosclz_bitshuffle_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;101;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_lz4_bitshuffle_1 "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "lz4" "bitshuffle" "test" "1")
set_tests_properties(test_lz4_bitshuffle_1 PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;103;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_blosclz_bitshuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "blosclz" "bitshuffle" "test")
set_tests_properties(test_blosclz_bitshuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;120;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_lz4_bitshuffle_n "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/b2bench" "lz4" "bitshuffle" "test")
set_tests_properties(test_lz4_bitshuffle_n PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;122;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_bench_delta "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/delta_schunk")
set_tests_properties(test_bench_delta PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;150;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_bench_trunc_prec "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/trunc_prec_schunk")
set_tests_properties(test_bench_trunc_prec PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;156;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
add_test(test_bench_zero_runlen "/home/runner/work/c-blosc2/c-blosc2/_codeql_build_dir/bench/zero_runlen")
set_tests_properties(test_bench_zero_runlen PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;168;add_test;/home/runner/work/c-blosc2/c-blosc2/bench/CMakeLists.txt;0;")
subdirs("b2nd")
